version: "2.2"

services:
  petclinic: 
    build: 
      context: .
      dockerfile: Dockerfile 
      target: development
    ports:
      - 80:8080
      # - 8000:8000
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=do
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
  mysqlserver:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - GOOGLE_APPLICATION_CREDENTIALS: ../Documents/terraform/key.json
    volumes:
      - mysql_data:/var/lib/mysql
      # - "./conf.d:/etc/mysql/conf.d"
      
    # Inject your specific service account keyfile into the container at runtime.
      - ../Documents/terraform/key.json:/tmp/keys/keyfile.json:ro
    # profiles:
    #   - mysqlserver
  # postgres:
  #   image: postgres:16.1
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=petclinic
  #     - POSTGRES_USER=petclinic
  #     - POSTGRES_DB=petclinic
  #   profiles:
  #     - postgres
volumes: 
  mysql_data:
  mysql_config: